version: "3"
services:
  starlightproxy:
    image: "ghcr.io/mc256/starlight/proxy:latest"
    ports:
      - 8090:8090
    command:
      - /opt/starlight-proxy
    environment:
      - STARLIGHT_HOST=0.0.0.0
      - STARLIGHT_PORT=8090
      - LOG_LEVEL=info
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      # - REGISTRY=http://registry:5000 # proxy parsing has some issue
    restart: always
    depends_on:
      - db
      - registry