version: "3"
services:
  starlightproxy:
    image: ghcr.io/mc256/starlight/proxy:latest
    container_name: starlightproxy
    ports:
      - 8090:8090
    environment:
      #- REGISTRY=http://starlightregistry:5000
      - LOGLEVEL=info
    volumes:
      - "./data:/go/src/app/data:rw"
    restart: always