version: "3"
services:
  registry2:
    image: registry:2
    container_name: registry2
    ports:
    - 5000:5000
    environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    volumes:
    - "./data:/data:rw"
    restart: always