apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: starlight-pvc
  name: starlight-pvc
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Mi