{{- if .Values.postgres.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "starlight.fullname" . }}
  labels:
    {{- include "starlight.proxyLabels" . | nindent 4 }}
  annotations:
  {{- if .Values.postgres.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    {{- range .Values.postgres.persistence.accessModes }}
    - {{ . }}
    {{- end }}  
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- end -}}
