apiVersion: v1
kind: Service
metadata:
  name: {{ include "starlight-proxy-chart.fullname" . }}
  labels:
    {{- include "starlight-proxy-chart.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: proxy-http
    {{- if .Values.registry.enabled}}
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registry-http
    {{- end}}
    {{- if .Values.registryUi.enabled}}
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: registry-ui-http
    {{- end}}
  selector:
    {{- include "starlight-proxy-chart.selectorLabels" . | nindent 4 }}
