version: "3"
services:
  proxy:
    extra_hosts:
      - 'cloud.cluster.local:192.168.56.102'
    image: "ghcr.io/mc256/starlight/proxy:latest"
    ports:
      - 8090:8090
    command:
      - /opt/starlight-proxy
    environment:
      - STARLIGHT_HOST=0.0.0.0
      - STARLIGHT_PORT=8090
      - LOG_LEVEL=info
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      # - REGISTRY=http://registry:5000 # proxy parsing has some issue
    restart: always
    depends_on:
      - db
      - registry
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "./metadata:/var/lib/postgresql/data"
  dbadmin:
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
        - db
  registry:
    image: registry:2
    ports:
    - 5000:5000
    - 80:5000
    environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    volumes:
    - "./data_registry:/data:rw"
    restart: always
