name: Debian Package
on:
  push:
    branches:
      - feature_debian_*
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build deb package
        run: |
          export GO111MODULE=on
          export REGISTRY=registry2
          export LOGLEVEL=info
          export PATH="/usr/local/go/bin:$PATH" 
          export EMAIL=webmaster@mc256.dev
          export TZ="Etc/UTC"
          sudo apt-get update -y 
          sudo apt-get upgrade -y 
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata
          sudo apt-get install -y ssh vim tmux zsh git curl dpkg-dev gpg build-essential debhelper
          wget https://go.dev/dl/go1.18.4.linux-amd64.tar.gz && sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.4.linux-amd64.tar.gz 
          sudo make create-deb-package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./sandbox/*.deb