name: Publish Docker image (release)
on:
  push:
    branches:
      - master
      - release
      - 'build/*'
      - feature_documentation
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Private Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.yuri.moe
          username: github
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.yuri.moe/starlight-proxy:latest
            ghcr.io/mc256/starlight/proxy:latest